# Generated by Django 5.2.6 on 2025-09-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=60)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=120)),
                ("role", models.CharField(default="user", max_length=50)),
            ],
        ),
    ]
