# Generated by Django 5.2.6 on 2025-09-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_sweets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sweets",
            name="price",
            field=models.CharField(max_length=50),
        ),
    ]
